server:
  port: 9091

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#打开hystrix断路器
feign:
  hystrix:
    enabled: true